// marketer-signup — public endpoint that creates a marketer account.
//
// Atomic flow:
//   1. Validate every input field server-side.
//   2. Pre-flight uniqueness check on phone + email in public.marketers
//      (a friendlier error than catching the unique-constraint violation
//      after we've already provisioned an auth.users row).
//   3. admin.auth.admin.createUser() with email_confirm=false so Supabase
//      sends the confirmation email (routed via the Resend SMTP configured
//      at the project level).
//   4. Insert public.marketers row. referral_code is generated by the
//      DB default (generate_unique_marketer_code).
//   5. If the insert fails, roll back the auth.users row to keep the two
//      tables consistent.
//
// Public endpoint: verify_jwt = false in supabase/config.toml. CORS is
// allowlisted via _shared/cors.ts (production origins + localhost/preview
// on non-prod envs).

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { corsHeadersFor, preflightResponse } from "../_shared/cors.ts";
import { normalizeKsaPhone, ValidationError } from "../_shared/validation.ts";

interface Payload {
  full_name?: string;
  phone?: string;
  email?: string;
  password?: string;
  city?: string;
  age?: number | string;
  has_marketing_experience?: boolean;
}

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const MIN_PASSWORD = 8;
const MIN_AGE = 18;

Deno.serve(async (req: Request) => {
  const cors = corsHeadersFor(req, "POST, OPTIONS");
  if (req.method === "OPTIONS") return preflightResponse(req, "POST, OPTIONS");

  try {
    const body = (await req.json()) as Payload;

    const fullName = (body.full_name ?? "").trim();
    if (fullName.length < 2 || fullName.length > 80) {
      throw new ValidationError("الاسم الكامل مطلوب (حرفين على الأقل).", "full_name");
    }

    const phone = normalizeKsaPhone(body.phone);
    if (!phone) {
      throw new ValidationError("رقم الجوال غير صحيح. يجب أن يبدأ بـ 05 ويتكون من 10 أرقام.", "phone");
    }

    const email = (body.email ?? "").trim().toLowerCase();
    if (!EMAIL_RE.test(email)) {
      throw new ValidationError("البريد الإلكتروني غير صحيح.", "email");
    }

    const password = body.password ?? "";
    if (password.length < MIN_PASSWORD) {
      throw new ValidationError(`كلمة المرور قصيرة جداً (${MIN_PASSWORD} أحرف على الأقل).`, "password");
    }

    const city = (body.city ?? "").trim();
    if (city.length < 2 || city.length > 60) {
      throw new ValidationError("المدينة مطلوبة.", "city");
    }

    const ageNum = typeof body.age === "string" ? parseInt(body.age, 10) : body.age;
    if (!Number.isFinite(ageNum as number) || (ageNum as number) < MIN_AGE || (ageNum as number) > 100) {
      throw new ValidationError(`يجب أن يكون العمر ${MIN_AGE} سنة فأكثر.`, "age");
    }

    const hasExperience = Boolean(body.has_marketing_experience);

    const svc = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
      { auth: { persistSession: false } },
    );

    // Pre-flight uniqueness check (friendlier than the constraint-violation path).
    const { data: existing } = await svc
      .from("marketers")
      .select("id, phone, email")
      .or(`phone.eq.${phone},email.eq.${email}`)
      .maybeSingle();

    if (existing) {
      const conflictField = existing.email === email ? "email" : "phone";
      const message = conflictField === "email"
        ? "هذا البريد الإلكتروني مستخدم مسبقاً."
        : "رقم الجوال مستخدم مسبقاً.";
      throw new ValidationError(message, conflictField);
    }

    // Create the auth user. email_confirm=false → Supabase sends the
    // confirmation email automatically via the project's SMTP provider.
    const { data: created, error: createErr } = await svc.auth.admin.createUser({
      email,
      password,
      email_confirm: false,
      user_metadata: {
        full_name: fullName,
        role: "marketer",
      },
    });
    if (createErr || !created?.user) {
      throw new Error(createErr?.message || "تعذّر إنشاء الحساب.");
    }

    // Insert the marketers row. referral_code is generated by the DB default.
    const { data: marketer, error: insertErr } = await svc
      .from("marketers")
      .insert({
        user_id: created.user.id,
        full_name: fullName,
        phone,
        email,
        city,
        age: ageNum,
        has_marketing_experience: hasExperience,
      })
      .select("id, referral_code")
      .single();

    if (insertErr || !marketer) {
      // Roll back the auth.users row so a retry can succeed cleanly.
      await svc.auth.admin.deleteUser(created.user.id);
      throw new Error(insertErr?.message || "تعذّر حفظ بيانات المسوّق.");
    }

    return new Response(
      JSON.stringify({
        success: true,
        user_id: created.user.id,
        marketer_id: marketer.id,
        referral_code: marketer.referral_code,
        email,
      }),
      { headers: { ...cors, "Content-Type": "application/json" } },
    );
  } catch (err) {
    const isValidation = err instanceof ValidationError;
    const msg = (err as Error).message;
    const field = isValidation ? (err as ValidationError).field : undefined;
    return new Response(
      JSON.stringify({ success: false, error: msg, field }),
      {
        status: isValidation ? 400 : 500,
        headers: { ...cors, "Content-Type": "application/json" },
      },
    );
  }
});
