// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/niqaty-hero/ProofWall.tsx": () => import("../components/mockups/niqaty-hero/ProofWall.tsx"),
  "./components/mockups/niqaty-hero/RevenueBleed.tsx": () => import("../components/mockups/niqaty-hero/RevenueBleed.tsx"),
  "./components/mockups/niqaty-hero/WalletFirst.tsx": () => import("../components/mockups/niqaty-hero/WalletFirst.tsx"),
  "./components/mockups/niqaty-landing/AffordanceBento.tsx": () => import("../components/mockups/niqaty-landing/AffordanceBento.tsx"),
  "./components/mockups/niqaty-landing/AffordanceChapters.tsx": () => import("../components/mockups/niqaty-landing/AffordanceChapters.tsx"),
  "./components/mockups/niqaty-landing/AffordanceSplit.tsx": () => import("../components/mockups/niqaty-landing/AffordanceSplit.tsx"),
  "./components/mockups/niqaty-landing/BoldEditorial.tsx": () => import("../components/mockups/niqaty-landing/BoldEditorial.tsx"),
  "./components/mockups/niqaty-landing/ClassicPremium.tsx": () => import("../components/mockups/niqaty-landing/ClassicPremium.tsx"),
  "./components/mockups/niqaty-landing/CleanMinimal.tsx": () => import("../components/mockups/niqaty-landing/CleanMinimal.tsx"),
  "./components/mockups/niqaty-landing/MidnightDrop.tsx": () => import("../components/mockups/niqaty-landing/MidnightDrop.tsx"),
  "./components/mockups/niqaty-landing/StillWaters.tsx": () => import("../components/mockups/niqaty-landing/StillWaters.tsx"),
  "./components/mockups/niqaty-landing/WarmSouq.tsx": () => import("../components/mockups/niqaty-landing/WarmSouq.tsx"),
  "./components/mockups/niqaty-landing/WarmSouqA11y.tsx": () => import("../components/mockups/niqaty-landing/WarmSouqA11y.tsx"),
  "./components/mockups/niqaty-landing/WarmSouqAffordance.tsx": () => import("../components/mockups/niqaty-landing/WarmSouqAffordance.tsx"),
  "./components/mockups/niqaty-landing/WarmSouqHierarchy.tsx": () => import("../components/mockups/niqaty-landing/WarmSouqHierarchy.tsx")
};
