-- Marketer affiliate program — table 1/4: marketers.
--
-- A marketer is a person we hire on commission to refer merchants to Waya.
-- One row per marketer, 1:1 with auth.users (Supabase Auth holds the
-- credentials and email-verification state). Inserts only happen via the
-- marketer-signup edge function (service-role); RLS lets the marketer
-- read and update their own row from the dashboard.
--
-- Each marketer gets a unique 4-uppercase-letter referral_code generated by
-- generate_unique_marketer_code() — random with up-to-50 retries on
-- collision. 26^4 = 456,976 codes, plenty for the foreseeable scale.

begin;

create or replace function public.generate_unique_marketer_code()
returns char(4)
language plpgsql
as $$
declare
  candidate char(4);
  attempts  int := 0;
begin
  loop
    candidate := upper(
      chr(65 + floor(random() * 26)::int) ||
      chr(65 + floor(random() * 26)::int) ||
      chr(65 + floor(random() * 26)::int) ||
      chr(65 + floor(random() * 26)::int)
    );
    perform 1 from public.marketers where referral_code = candidate;
    if not found then
      return candidate;
    end if;
    attempts := attempts + 1;
    if attempts > 50 then
      raise exception 'Could not generate a unique marketer code after 50 attempts';
    end if;
  end loop;
end $$;

create table if not exists public.marketers (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null unique references auth.users(id) on delete cascade,
  full_name                text not null,
  phone                    text not null unique,
  email                    text not null unique,
  city                     text not null,
  age                      int  not null check (age >= 18),
  has_marketing_experience boolean not null default false,
  referral_code            char(4) not null unique
                                   default public.generate_unique_marketer_code()
                                   check (referral_code ~ '^[A-Z]{4}$'),
  payment_account_name     text,
  bank_name                text,
  iban                     text check (iban is null or iban ~ '^SA[0-9]{22}$'),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create index if not exists marketers_referral_code_idx on public.marketers(referral_code);
create index if not exists marketers_user_id_idx       on public.marketers(user_id);

alter table public.marketers enable row level security;

drop policy if exists "marketer reads self" on public.marketers;
create policy "marketer reads self"
  on public.marketers for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "marketer updates self" on public.marketers;
create policy "marketer updates self"
  on public.marketers for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- No insert policy: signups go through the marketer-signup edge function
-- (service_role), which bypasses RLS. This keeps client-side code from
-- inserting half-formed marketer records that bypass code generation.

commit;
